apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app2
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app2
          image: kirillvelichko/app2:latest
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 9000
              name: grpc
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 80
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3